### ISSUE TITLE
Unable to compile savedatacheck.cpp:47:117: error

### ISSUE THREAD

**Issue by alecblah** [citra-emu/3dsutils#12]
I did a full install of the devkitPro tool chain from the windows gui installer ran make and below is the resulting log file of the results

[log.txt](https://github.com/citra-emu/3dsutils/files/454482/log.txt)

not sure if there are some prerequisites I missed

**Comment by wwylele** [comment]
I changed the code in #8 , according to the newest ctrulib API. It seems that you got an older version of ctrulib. I am not sure how windows gui installer works, but can you update it?

**Comment by alecblah** [comment]
It was the most recent however I may be able to patch in the latest ctrulib I'll have to look into it in the morning I. I had a hunch that might be my issue, but ctrulip git page kept suggesting I just use the gui installer.

Additionally I did try to compile it on linux first but that failed as well. My build setup there was installed by running the following commands within 6 hours before posting the issue

curl -L https://raw.githubusercontent.com/devkitPro/installer/master/perl/devkitARMupdate.pl -o devkitARMupdate.pl

chmod +x ./devkitARMupdate.pl

sudo ./devkitARMupdate.pl /opt/devkitpro

echo "export DEVKITPRO=/opt/devkitpro" >> ~/.bashrc

echo "export DEVKITARM=/opt/devkitpro/devkitARM" >> ~/.bashrc

echo "export PATH=$PATH:/opt/devkitpro/devkitARM/bin" >> ~/.bashrc

source ~/.bashrc

after that I just opened a terminal in the folder and ran make, got the same error as my windows box. also the devkitARMupdate.pl script on the linux (mint) all reported being up to date. I reran devkitARMupdate.pl as that was my first thought.

Also Kudos on the fast reply

**Comment by wwylele** [comment]
My ctrulib is built from source, which is updated from https://github.com/smealum/ctrulib . Before #8, I also received bug report about compiling error (exactly the inverse version of yours), so I thought ctrulib was fully updated. Now turns out the version on the server isn't updated with the code on github?

Could you please try revert #8 to see if it helps?

**Comment by alecblah** [comment]
That worked.  Odd that there server isn't updated with the github code. Any eta on when the precompiled builds will be hosted? Thanks for the help.
